// flow-typed signature: 04f0be8e4e9308a762b4918009fc433a
// flow-typed version: <<STUB>>/babel_v^4.3.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/bin/babel/dir' {
  declare module.exports: any;
}

declare module 'babel/bin/babel/file' {
  declare module.exports: any;
}

declare module 'babel/bin/babel/index' {
  declare module.exports: any;
}

declare module 'babel/bin/babel/util' {
  declare module.exports: any;
}

declare module 'babel/browser-polyfill' {
  declare module.exports: any;
}

declare module 'babel/browser' {
  declare module.exports: any;
}

declare module 'babel/external-helpers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/browser' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/node' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/register/browser' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/register/cache' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/register/node' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/api/register/resolve-rc' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/buffer' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/base' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/classes' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/comprehensions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/expressions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/flow' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/jsx' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/methods' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/modules' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/playground' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/statements' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/template-literals' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/generators/types' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/node/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/node/parentheses' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/node/whitespace' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/position' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/source-map' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/generation/whitespace' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/helpers/code-frame' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/helpers/normalize-ast' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/helpers/object' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/helpers/parse' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/messages' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/patch' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/polyfill' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/tools/build-external-helpers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/tools/resolve-rc' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/file' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/file/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/file/logger' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/file/option-parsers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/build-binary-assignment-operator-transformer' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/build-comprehension' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/build-conditional-assignment-operator-transformer' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/build-react-transformer' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/define-map' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/explode-assignable-expression' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/get-function-arity' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/name-method' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/react' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/regex' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/remap-async-to-generator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/replace-supers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/helpers/strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/logger' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/_default' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/_strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/amd-strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/amd' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/common-strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/common' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/ignore' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/system' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/umd-strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/modules/umd' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformer-pass' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformer' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es3/member-expression-literals' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es3/property-literals' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es5/properties.mutators' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/arrow-functions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/block-scoping-tdz' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/block-scoping' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/classes' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/constants' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/destructuring' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/for-of' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/modules' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/object-super' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/parameters.default' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/parameters.rest' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/properties.computed' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/properties.shorthand' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/regex.sticky' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/regex.unicode' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/spread' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/symbols' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/tail-call' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es6/template-literals' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es7/abstract-references' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es7/async-functions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es7/comprehensions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es7/exponentiation-operator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/es7/object-rest-spread' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/alias-functions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/block-hoist' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/cleanup' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/declarations' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/module-formatter' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/modules' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/internal/validation' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/optimisation/flow.for-of' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/async-to-generator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/bluebird-coroutines' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/flow' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/react-compat' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/react' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/regenerator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/runtime' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/other/strict' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/playground/mallet-operator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/playground/memoization-operator' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/playground/method-binding' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/playground/object-getter-memoization' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/spec/block-scoped-functions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/spec/function-name' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/spec/proto-to-assign' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/spec/undefined-to-void' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/utility/dead-code-elimination' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/utility/inline-environment-variables' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/utility/inline-expressions' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/utility/remove-console' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/utility/remove-debugger' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/validation/react' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/transformation/transformers/validation/undeclared-variable-check' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/binding' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/context' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/path' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/path/conversion' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/path/evaluation' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/path/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/traversal/scope' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/types/converters' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/types/evaluators' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/types/index' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/types/retrievers' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/types/validators' {
  declare module.exports: any;
}

declare module 'babel/lib/babel/util' {
  declare module.exports: any;
}

declare module 'babel/polyfill' {
  declare module.exports: any;
}

declare module 'babel/register' {
  declare module.exports: any;
}

declare module 'babel/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/bin/babel/dir.js' {
  declare module.exports: $Exports<'babel/bin/babel/dir'>;
}
declare module 'babel/bin/babel/file.js' {
  declare module.exports: $Exports<'babel/bin/babel/file'>;
}
declare module 'babel/bin/babel/index.js' {
  declare module.exports: $Exports<'babel/bin/babel/index'>;
}
declare module 'babel/bin/babel/util.js' {
  declare module.exports: $Exports<'babel/bin/babel/util'>;
}
declare module 'babel/browser-polyfill.js' {
  declare module.exports: $Exports<'babel/browser-polyfill'>;
}
declare module 'babel/browser.js' {
  declare module.exports: $Exports<'babel/browser'>;
}
declare module 'babel/external-helpers.js' {
  declare module.exports: $Exports<'babel/external-helpers'>;
}
declare module 'babel/lib/babel/api/browser.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/browser'>;
}
declare module 'babel/lib/babel/api/node.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/node'>;
}
declare module 'babel/lib/babel/api/register/browser.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/register/browser'>;
}
declare module 'babel/lib/babel/api/register/cache.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/register/cache'>;
}
declare module 'babel/lib/babel/api/register/node.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/register/node'>;
}
declare module 'babel/lib/babel/api/register/resolve-rc.js' {
  declare module.exports: $Exports<'babel/lib/babel/api/register/resolve-rc'>;
}
declare module 'babel/lib/babel/generation/buffer.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/buffer'>;
}
declare module 'babel/lib/babel/generation/generators/base.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/base'>;
}
declare module 'babel/lib/babel/generation/generators/classes.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/classes'>;
}
declare module 'babel/lib/babel/generation/generators/comprehensions.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/comprehensions'>;
}
declare module 'babel/lib/babel/generation/generators/expressions.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/expressions'>;
}
declare module 'babel/lib/babel/generation/generators/flow.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/flow'>;
}
declare module 'babel/lib/babel/generation/generators/jsx.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/jsx'>;
}
declare module 'babel/lib/babel/generation/generators/methods.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/methods'>;
}
declare module 'babel/lib/babel/generation/generators/modules.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/modules'>;
}
declare module 'babel/lib/babel/generation/generators/playground.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/playground'>;
}
declare module 'babel/lib/babel/generation/generators/statements.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/statements'>;
}
declare module 'babel/lib/babel/generation/generators/template-literals.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/template-literals'>;
}
declare module 'babel/lib/babel/generation/generators/types.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/generators/types'>;
}
declare module 'babel/lib/babel/generation/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/index'>;
}
declare module 'babel/lib/babel/generation/node/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/node/index'>;
}
declare module 'babel/lib/babel/generation/node/parentheses.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/node/parentheses'>;
}
declare module 'babel/lib/babel/generation/node/whitespace.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/node/whitespace'>;
}
declare module 'babel/lib/babel/generation/position.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/position'>;
}
declare module 'babel/lib/babel/generation/source-map.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/source-map'>;
}
declare module 'babel/lib/babel/generation/whitespace.js' {
  declare module.exports: $Exports<'babel/lib/babel/generation/whitespace'>;
}
declare module 'babel/lib/babel/helpers/code-frame.js' {
  declare module.exports: $Exports<'babel/lib/babel/helpers/code-frame'>;
}
declare module 'babel/lib/babel/helpers/normalize-ast.js' {
  declare module.exports: $Exports<'babel/lib/babel/helpers/normalize-ast'>;
}
declare module 'babel/lib/babel/helpers/object.js' {
  declare module.exports: $Exports<'babel/lib/babel/helpers/object'>;
}
declare module 'babel/lib/babel/helpers/parse.js' {
  declare module.exports: $Exports<'babel/lib/babel/helpers/parse'>;
}
declare module 'babel/lib/babel/messages.js' {
  declare module.exports: $Exports<'babel/lib/babel/messages'>;
}
declare module 'babel/lib/babel/patch.js' {
  declare module.exports: $Exports<'babel/lib/babel/patch'>;
}
declare module 'babel/lib/babel/polyfill.js' {
  declare module.exports: $Exports<'babel/lib/babel/polyfill'>;
}
declare module 'babel/lib/babel/tools/build-external-helpers.js' {
  declare module.exports: $Exports<'babel/lib/babel/tools/build-external-helpers'>;
}
declare module 'babel/lib/babel/tools/resolve-rc.js' {
  declare module.exports: $Exports<'babel/lib/babel/tools/resolve-rc'>;
}
declare module 'babel/lib/babel/transformation/file.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/file'>;
}
declare module 'babel/lib/babel/transformation/file/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/file/index'>;
}
declare module 'babel/lib/babel/transformation/file/logger.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/file/logger'>;
}
declare module 'babel/lib/babel/transformation/file/option-parsers.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/file/option-parsers'>;
}
declare module 'babel/lib/babel/transformation/helpers/build-binary-assignment-operator-transformer.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/build-binary-assignment-operator-transformer'>;
}
declare module 'babel/lib/babel/transformation/helpers/build-comprehension.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/build-comprehension'>;
}
declare module 'babel/lib/babel/transformation/helpers/build-conditional-assignment-operator-transformer.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/build-conditional-assignment-operator-transformer'>;
}
declare module 'babel/lib/babel/transformation/helpers/build-react-transformer.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/build-react-transformer'>;
}
declare module 'babel/lib/babel/transformation/helpers/define-map.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/define-map'>;
}
declare module 'babel/lib/babel/transformation/helpers/explode-assignable-expression.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/explode-assignable-expression'>;
}
declare module 'babel/lib/babel/transformation/helpers/get-function-arity.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/get-function-arity'>;
}
declare module 'babel/lib/babel/transformation/helpers/name-method.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/name-method'>;
}
declare module 'babel/lib/babel/transformation/helpers/react.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/react'>;
}
declare module 'babel/lib/babel/transformation/helpers/regex.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/regex'>;
}
declare module 'babel/lib/babel/transformation/helpers/remap-async-to-generator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/remap-async-to-generator'>;
}
declare module 'babel/lib/babel/transformation/helpers/replace-supers.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/replace-supers'>;
}
declare module 'babel/lib/babel/transformation/helpers/strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/helpers/strict'>;
}
declare module 'babel/lib/babel/transformation/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/index'>;
}
declare module 'babel/lib/babel/transformation/logger.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/logger'>;
}
declare module 'babel/lib/babel/transformation/modules/_default.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/_default'>;
}
declare module 'babel/lib/babel/transformation/modules/_strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/_strict'>;
}
declare module 'babel/lib/babel/transformation/modules/amd-strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/amd-strict'>;
}
declare module 'babel/lib/babel/transformation/modules/amd.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/amd'>;
}
declare module 'babel/lib/babel/transformation/modules/common-strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/common-strict'>;
}
declare module 'babel/lib/babel/transformation/modules/common.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/common'>;
}
declare module 'babel/lib/babel/transformation/modules/ignore.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/ignore'>;
}
declare module 'babel/lib/babel/transformation/modules/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/index'>;
}
declare module 'babel/lib/babel/transformation/modules/system.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/system'>;
}
declare module 'babel/lib/babel/transformation/modules/umd-strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/umd-strict'>;
}
declare module 'babel/lib/babel/transformation/modules/umd.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/modules/umd'>;
}
declare module 'babel/lib/babel/transformation/transformer-pass.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformer-pass'>;
}
declare module 'babel/lib/babel/transformation/transformer.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformer'>;
}
declare module 'babel/lib/babel/transformation/transformers/es3/member-expression-literals.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es3/member-expression-literals'>;
}
declare module 'babel/lib/babel/transformation/transformers/es3/property-literals.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es3/property-literals'>;
}
declare module 'babel/lib/babel/transformation/transformers/es5/properties.mutators.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es5/properties.mutators'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/arrow-functions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/arrow-functions'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/block-scoping-tdz.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/block-scoping-tdz'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/block-scoping.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/block-scoping'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/classes.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/classes'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/constants.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/constants'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/destructuring.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/destructuring'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/for-of.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/for-of'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/modules.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/modules'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/object-super.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/object-super'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/parameters.default.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/parameters.default'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/parameters.rest.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/parameters.rest'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/properties.computed.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/properties.computed'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/properties.shorthand.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/properties.shorthand'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/regex.sticky.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/regex.sticky'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/regex.unicode.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/regex.unicode'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/spread.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/spread'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/symbols.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/symbols'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/tail-call.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/tail-call'>;
}
declare module 'babel/lib/babel/transformation/transformers/es6/template-literals.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es6/template-literals'>;
}
declare module 'babel/lib/babel/transformation/transformers/es7/abstract-references.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es7/abstract-references'>;
}
declare module 'babel/lib/babel/transformation/transformers/es7/async-functions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es7/async-functions'>;
}
declare module 'babel/lib/babel/transformation/transformers/es7/comprehensions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es7/comprehensions'>;
}
declare module 'babel/lib/babel/transformation/transformers/es7/exponentiation-operator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es7/exponentiation-operator'>;
}
declare module 'babel/lib/babel/transformation/transformers/es7/object-rest-spread.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/es7/object-rest-spread'>;
}
declare module 'babel/lib/babel/transformation/transformers/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/index'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/alias-functions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/alias-functions'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/block-hoist.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/block-hoist'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/cleanup.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/cleanup'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/declarations.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/declarations'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/module-formatter.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/module-formatter'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/modules.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/modules'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/strict'>;
}
declare module 'babel/lib/babel/transformation/transformers/internal/validation.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/internal/validation'>;
}
declare module 'babel/lib/babel/transformation/transformers/optimisation/flow.for-of.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/optimisation/flow.for-of'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/async-to-generator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/async-to-generator'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/bluebird-coroutines.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/bluebird-coroutines'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/flow.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/flow'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/react-compat.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/react-compat'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/react.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/react'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/regenerator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/regenerator'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/runtime.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/runtime'>;
}
declare module 'babel/lib/babel/transformation/transformers/other/strict.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/other/strict'>;
}
declare module 'babel/lib/babel/transformation/transformers/playground/mallet-operator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/playground/mallet-operator'>;
}
declare module 'babel/lib/babel/transformation/transformers/playground/memoization-operator.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/playground/memoization-operator'>;
}
declare module 'babel/lib/babel/transformation/transformers/playground/method-binding.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/playground/method-binding'>;
}
declare module 'babel/lib/babel/transformation/transformers/playground/object-getter-memoization.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/playground/object-getter-memoization'>;
}
declare module 'babel/lib/babel/transformation/transformers/spec/block-scoped-functions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/spec/block-scoped-functions'>;
}
declare module 'babel/lib/babel/transformation/transformers/spec/function-name.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/spec/function-name'>;
}
declare module 'babel/lib/babel/transformation/transformers/spec/proto-to-assign.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/spec/proto-to-assign'>;
}
declare module 'babel/lib/babel/transformation/transformers/spec/undefined-to-void.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/spec/undefined-to-void'>;
}
declare module 'babel/lib/babel/transformation/transformers/utility/dead-code-elimination.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/utility/dead-code-elimination'>;
}
declare module 'babel/lib/babel/transformation/transformers/utility/inline-environment-variables.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/utility/inline-environment-variables'>;
}
declare module 'babel/lib/babel/transformation/transformers/utility/inline-expressions.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/utility/inline-expressions'>;
}
declare module 'babel/lib/babel/transformation/transformers/utility/remove-console.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/utility/remove-console'>;
}
declare module 'babel/lib/babel/transformation/transformers/utility/remove-debugger.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/utility/remove-debugger'>;
}
declare module 'babel/lib/babel/transformation/transformers/validation/react.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/validation/react'>;
}
declare module 'babel/lib/babel/transformation/transformers/validation/undeclared-variable-check.js' {
  declare module.exports: $Exports<'babel/lib/babel/transformation/transformers/validation/undeclared-variable-check'>;
}
declare module 'babel/lib/babel/traversal/binding.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/binding'>;
}
declare module 'babel/lib/babel/traversal/context.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/context'>;
}
declare module 'babel/lib/babel/traversal/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/index'>;
}
declare module 'babel/lib/babel/traversal/path.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/path'>;
}
declare module 'babel/lib/babel/traversal/path/conversion.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/path/conversion'>;
}
declare module 'babel/lib/babel/traversal/path/evaluation.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/path/evaluation'>;
}
declare module 'babel/lib/babel/traversal/path/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/path/index'>;
}
declare module 'babel/lib/babel/traversal/scope.js' {
  declare module.exports: $Exports<'babel/lib/babel/traversal/scope'>;
}
declare module 'babel/lib/babel/types/converters.js' {
  declare module.exports: $Exports<'babel/lib/babel/types/converters'>;
}
declare module 'babel/lib/babel/types/evaluators.js' {
  declare module.exports: $Exports<'babel/lib/babel/types/evaluators'>;
}
declare module 'babel/lib/babel/types/index.js' {
  declare module.exports: $Exports<'babel/lib/babel/types/index'>;
}
declare module 'babel/lib/babel/types/retrievers.js' {
  declare module.exports: $Exports<'babel/lib/babel/types/retrievers'>;
}
declare module 'babel/lib/babel/types/validators.js' {
  declare module.exports: $Exports<'babel/lib/babel/types/validators'>;
}
declare module 'babel/lib/babel/util.js' {
  declare module.exports: $Exports<'babel/lib/babel/util'>;
}
declare module 'babel/polyfill.js' {
  declare module.exports: $Exports<'babel/polyfill'>;
}
declare module 'babel/register.js' {
  declare module.exports: $Exports<'babel/register'>;
}
declare module 'babel/test.js' {
  declare module.exports: $Exports<'babel/test'>;
}
