// flow-typed signature: 8d5a0662db6f91d380b62c21a12601be
// flow-typed version: <<STUB>>/chromeless_v^1.5.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chromeless'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chromeless' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chromeless/dist/src/api' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/chrome/local-runtime' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/chrome/local' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/chrome/remote' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/index' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/queue' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/types' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/util' {
  declare module.exports: any;
}

declare module 'chromeless/dist/src/util.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chromeless/dist/src/api.js' {
  declare module.exports: $Exports<'chromeless/dist/src/api'>;
}
declare module 'chromeless/dist/src/chrome/local-runtime.js' {
  declare module.exports: $Exports<'chromeless/dist/src/chrome/local-runtime'>;
}
declare module 'chromeless/dist/src/chrome/local.js' {
  declare module.exports: $Exports<'chromeless/dist/src/chrome/local'>;
}
declare module 'chromeless/dist/src/chrome/remote.js' {
  declare module.exports: $Exports<'chromeless/dist/src/chrome/remote'>;
}
declare module 'chromeless/dist/src/index.js' {
  declare module.exports: $Exports<'chromeless/dist/src/index'>;
}
declare module 'chromeless/dist/src/queue.js' {
  declare module.exports: $Exports<'chromeless/dist/src/queue'>;
}
declare module 'chromeless/dist/src/types.js' {
  declare module.exports: $Exports<'chromeless/dist/src/types'>;
}
declare module 'chromeless/dist/src/util.js' {
  declare module.exports: $Exports<'chromeless/dist/src/util'>;
}
declare module 'chromeless/dist/src/util.test.js' {
  declare module.exports: $Exports<'chromeless/dist/src/util.test'>;
}
