// flow-typed signature: fb6a0dec323c11acc3ca1130d98768c1
// flow-typed version: <<STUB>>/dataloader_v1.4.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dataloader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dataloader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dataloader/index' {
  declare module.exports: $Exports<'dataloader'>;
}
declare module 'dataloader/index.js' {
  declare module.exports: $Exports<'dataloader'>;
}
